#!/bin/bash

PROJECT_NAME=$1
SERVICE_NAME=$2
SERVICE_PORT=$3

TEMPLATE_DIR=template
SRC_DIR=$PROJECT_NAME/src
BIN_DIR=$PROJECT_NAME/bin
PROTO_DIR=$SRC_DIR/service_spec
PROTO_FILE=$PROTO_DIR/$PROJECT_NAME.proto
SERVER_CC_FILE=$SRC_DIR/server.cc
CLIENT_CC_FILE=$SRC_DIR/client.cc
MAKEFILE_FILE=$SRC_DIR/Makefile

TEMPLATE_PROTO=$TEMPLATE_DIR/proto.txt
TEMPLATE_MAKEFILE=$TEMPLATE_DIR/makefile.txt
TEMPLATE_SERVER=$TEMPLATE_DIR/server.txt
TEMPLATE_CLIENT=$TEMPLATE_DIR/client.txt

PROJECT_TAG=__PROJECT__
SERVICE_PORT_TAG=__SERVICE_PORT__

if [ -d "$PROJECT_NAME" ] || [ -f $PROJECT_NAME ]; then
    echo "ERROR: $PROJECT_NAME already exists"
    exit 1
fi

mkdir -p $PROTO_DIR
mkdir -p $SRC_DIR
mkdir -p $BIN_DIR

cat $TEMPLATE_PROTO | sed "s/$PROJECT_TAG/$PROJECT_NAME/g" > $PROTO_FILE
cat $TEMPLATE_MAKEFILE | sed "s/$PROJECT_TAG/$PROJECT_NAME/g" > $MAKEFILE_FILE
cat $TEMPLATE_SERVER | sed "s/$PROJECT_TAG/$PROJECT_NAME/g" | sed "s/$SERVICE_PORT_TAG/$SERVICE_PORT/" > $SERVER_CC_FILE
cat $TEMPLATE_CLIENT | sed "s/$PROJECT_TAG/$PROJECT_NAME/g" | sed "s/$SERVICE_PORT_TAG/$SERVICE_PORT/" > $CLIENT_CC_FILE
